FROM adoptopenjdk/openjdk8-openj9

USER root
RUN  apt-get -qq update \
  && apt-get -qq install -y curl maven wget unzip xmlstarlet \
  && DEBIAN_FRONTEND=noninteractive apt-get -qq upgrade -y \
  && apt-get -qq clean \
  && rm -rf /tmp/* /var/lib/apt/lists/*

COPY ./LICENSE /licenses/
COPY ./project /project
COPY ./config /config

WORKDIR /project

# Build utility for version range processing
# Install parent pom
# Install maven wrapper in /project
RUN mkdir -p /mvn/repository \
 && /project/util/check_version build \
 && cd /project \
 && mvn -B -Dmaven.repo.local=/mvn/repository install dependency:go-offline -DskipTests \
 && mvn -B -N io.takari:maven:wrapper -Dmaven=$(mvn help:evaluate -Dexpression=maven.version -q -DforceStdout)
# RUN mvn -B -Pstack-image-package -Dmaven.repo.local=/mvn/repository liberty:install-server install dependency:go-offline
# RUN chmod -R 777 /opt/ol && chmod -R 777 /mvn/repository


WORKDIR /project/user-app

ENV APPSODY_MOUNTS="~/.m2/repository:/mvn/repository;.:/project/user-app"
ENV APPSODY_DEPS=

ENV APPSODY_WATCH_DIR=/project/user-app
ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/target
ENV APPSODY_WATCH_REGEX="^.*(.xml|.java|.properties)$"

ENV APPSODY_INSTALL="../validate.sh && mvn -B -Dmaven.repo.local=/mvn/repository install -DskipTests"

#ENV APPSODY_RUN="mvn -B -DappsDirectory=apps -Dmaven.repo.local=/mvn/repository  liberty:create && find /project/user-app -name '*.[e]ar' -exec cp -prv '{}' '/project/user-app/#target/liberty/wlp/usr/servers/defaultServer/apps/' ';' && mvn -B -DappsDirectory=apps -Dmaven.repo.local=/mvn/repository liberty:start"
ENV APPSODY_RUN="mvn -Dmaven.repo.local=/mvn/repository package -DskipTests liberty:run"
ENV APPSODY_RUN_ON_CHANGE="mvn -Dmaven.repo.local=/mvn/repository package -DskipTests"
ENV APPSODY_RUN_KILL=false

ENV APPSODY_DEBUG="mvn -B -Dmaven.repo.local=/mvn/repository liberty:debug"
ENV APPSODY_DEBUG_ON_CHANGE="mvn -Dmaven.repo.local=/mvn/repository package -DskipTests"
ENV APPSODY_DEBUG_KILL=false

ENV APPSODY_TEST="mvn -B -Dmaven.repo.local=/mvn/repository verify"
ENV APPSODY_TEST_ON_CHANGE=""
ENV APPSODY_TEST_KILL=false

ENV PORT=9080

EXPOSE 9080
EXPOSE 9443
EXPOSE 7777
